# Generated by Django 4.2 on 2023-04-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[(None, 'Выберите тип номера'), ('single', 'Одноместный стандарт'), ('single_comfort', 'Одноместный комфорт'), ('single_comfort_plus', 'Одноместный комфорт пдюс'), ('twin', 'Двухместный стандарт'), ('twin_comfort', 'Двухместный комфорт'), ('double', 'Двухместный комфорт плюс'), ('triple', 'Люкс')], max_length=20, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Название номера')),
                ('description', models.TextField(blank=True, verbose_name='Описание номера')),
                ('price', models.CharField(max_length=15, verbose_name='Стоимость номера в сутки')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
    ]
