# Generated by Django 4.2 on 2023-04-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_room', '0002_room_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['price'], 'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
        migrations.AlterField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото'),
        ),
    ]
