# Generated by Django 4.2 on 2023-04-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_room', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
