# Generated by Django 4.2 on 2023-04-29 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
